format = """
$hostname\
$localip\
$shlvl\
$shell\
$env_var\
$username\
$sudo\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\

$fill\ 
 
 $kubernetes\
$docker_context\
$deno\
$dotnet\
$elixir\
$elm\
$java\
$kotlin\
$nodejs\
$php\
$python\
$nix_shell\
$jobs\
$status\
$os\
$container\
$time\
$cmd_duration
$character
"""

add_newline = true

[directory]
read_only = " "
truncation_length = 1
format = '[ $path](bold gray)[$read_only]($read_only_style) '

[docker_context]
symbol = " "
format="[$symbol$version ]($style)"

[elixir]
symbol = " "
format="[$symbol$version ]($style)"

[elm]
symbol = " "
format="[$symbol$version ]($style)"

[java]
symbol = " "
format="[$symbol$version ]($style)"

[nix_shell]
symbol = " "
format="[$symbol$version ]($style)"

[nodejs]
symbol = " "
format="[$symbol$version ]($style)"

[python]
symbol = " "
format="[$symbol$version ]($style)"

[ruby]
symbol = " "
format="[$symbol$version ]($style)"

[rust]
symbol = " "
format="[$symbol$version ]($style)"

[time]
disabled = false  
format = "[$time](bright-gray)"
time_format = "%R"

[cmd_duration]
format = "[ $cmd_duration]($style)"

[fill]
symbol=' '

[git_branch]
symbol = " "
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
conflicted = "[x ](bold bright-red) "
ahead = "[$count](bright-cyan) "
behind = "[$count](yellow) "
diverged = " [$ahead_count $behind_count](red) "
untracked = "[?$count](blue) "
stashed = "[$count](bold bright-blue) "
modified = "[!$count](yellow) "
staged = "[+$count](bright-cyan) "
renamed = "[$count](yellow) "
deleted = "[$count](red) "
format = "$all_status$ahead_behind"
